name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        go mod download
        go mod verify
        
    - name: Run unit tests (no Redis)
      run: |
        go test -v -timeout=30s -run="^Test(New|Task|Backoff|Default|Option|Error)" ./...
        
    - name: Build
      run: go build -v ./...

  test-integration:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        go mod download
        go mod verify
        
    - name: Wait for Redis
      run: |
        docker run --network host --rm redis:7-alpine redis-cli -h localhost ping || exit 1
        sleep 5
        
    - name: Run integration tests
      run: |
        go test -v -timeout=60s -run="^Test(Queue|Worker|Integration)" ./...
      
    - name: Run tests with race detector
      run: |
        go test -race -timeout=60s -run="^Test(Queue|Worker|Integration)" ./...