name: Go Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
        
    - name: Install Redis CLI
      run: sudo apt-get update && sudo apt-get install -y redis-tools
        
    - name: Install dependencies
      run: |
        go mod download
        go mod verify
        
    - name: Wait for Redis
      run: |
        timeout 30s bash -c 'until redis-cli -h localhost ping; do sleep 1; done' || exit 1
        
    - name: Run unit tests
      run: go test -v -timeout=30s -run="^Test(New|Task|Queue|Worker|Backoff|Default|Option)" ./...
      
    - name: Run integration tests
      run: go test -v -timeout=60s -run="^TestIntegration" ./...
      
    - name: Run all tests with race detector
      run: go test -race -timeout=60s ./...
      
    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        
    - name: Build
      run: go build -v ./...