name: Basic Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        go mod download
        go mod verify
        
    - name: Run basic unit tests (no Redis)
      run: |
        go test -v -timeout=30s ./task.go ./task_test.go ./errors.go ./errors_test.go ./backoff.go ./backoff_test.go ./options.go ./options_test.go
        
    - name: Build package
      run: go build -v ./...